### ISSUE TITLE
How to use with browserify

### ISSUE THREAD

**Issue by hoangnguyencong** [jstools/jqlite#27]
I have a snippet code but got error:

var $ = require('jqlite');

var $myNode = $('.my-class');

Uncaught ReferenceError: $ is not defined

Expecting your help.

Best.

**Comment by jgermade** [comment]
Hi @hoangnguyencong, thanks for reporting this issue. I'll check this soon!

**Comment by jgermade** [comment]
Hi @hoangnguyencong, now jqlite should work with browserify ([jqlite v0.2.15](https://github.com/jstools/jqlite/releases/tag/v0.2.15))

Please let me know if doesn't work, and thanks for the feedback!!

**Comment by hoangnguyencong** [comment]
Hi @jgermade, thank for your helping. I updated latest version. But still not work. I get error when run:

var $ = require('jqlite');
var $myNode = $('.my-class');

Uncaught TypeError: object is not a function .

**Comment by jgermade** [comment]
Ok, I'll check this today and I'll test it with browserify.

Thanks @hoangnguyencong !

**Comment by jgermade** [comment]
Hi @hoangnguyencong, now it works (at least is working for me)

In order to enable jqlite as $ global object, I've used this code:
``` js
global.$ = require('jqlite');
```

thanks a lot for the feedback!!

**Comment by hoangnguyencong** [comment]
It worked. Many thanks @jgermade.
